# Generated by Django 5.1.2 on 2024-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.CharField(max_length=1000)),
                ("resposta", models.CharField(max_length=1000)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
