# Generated by Django 5.1.2 on 2024-10-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="pergunta",
            field=models.TextField(verbose_name="Pergunta"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="resposta",
            field=models.TextField(verbose_name="Resposta"),
        ),
    ]
