# Generated by Django 5.1.2 on 2024-11-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_todo_embedding_alter_todo_pergunta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="embedding",
        ),
        migrations.AddField(
            model_name="todo",
            name="cliente",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
