# Generated by Django 5.1.2 on 2024-11-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_remove_todo_embedding_todo_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="cliente",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
